const streetString = "10. utca,11. utca,12. utca,13. utca,14. utca,15. utca,16. utca,17. utca,18. utca,19. utca,1. utca,20. utca,21. utca,22. utca,23. utca,24. utca,25. utca,26. utca,27. utca,28. utca,29. utca,2. utca,30. utca,31. utca,32. utca,33. utca,34. utca,35. utca,36. utca,37. utca,38. utca,39. utca,3. utca,40. utca,41. utca,42. utca,43. utca,44. utca,45. utca,46. utca,47. utca,48. utca,49. utca,4. utca,50. utca,51. utca,52. utca,53. utca,54. utca,55. utca,57. utca,58. utca,59. utca,5. utca,60. utca,6. utca,7. utca,8. utca,9. utca,Aba utca,Ábel utca,Abony utca,Acél utca,Acsalapu utca,Ács utca,Adai utca,Ádám utca,Adél köz,Adorján utca,Ady tér,Áfonya utca,Aggófű utca,Ágnes utca,Ág utca,Agyagos utca,Ajtony köz,Akácfa utca,Akácos utca,Ákos utca,Alföldi utca,Algyői út,Alig utca,Alkony utca,Alkotmány utca,Állomás utca,Alma utca,Álmos köz,Alsó kikötő sor,Alsó-nyomási sor,Ambrus utca,Ámika utca,Ananász utca,András utca,Ánizs utca,Anna utca,Apáca utca,Apály utca,Apáthy István utca,Apatini utca,Apátság utca,Aradi vértanúk tere,Aranka utca,Arany János utca,Aranyműves köz,Aranyosi utca,Araszt utca,Arató utca,Árbóc utca,Árnika utca,Árnyas utca,Árok utca,Árpád tér,Árpa utca,Árvacsalán köz,Árvácska utca,Árvalányhaj utca,Árva utca,Árvíz utca,Ásványhát utca,Aszat köz,Asztalos utca,Atracél köz,Átrium köz,Attila utca,Avar utca,Babér utca,Babits Mihály utca,Back Bernát utca,Bacsó Béla utca,Bagoly utca,Bajai út,Bajmóci utca,Bajnok utca,Bajza utca,Bakay Nándor utca,Bakonyi utca,Baktói utca,Balabás utca,Balajthy utca,Balatoni utca,Balázs Béla utca,Bal fasor,Bálint Sándor utca,Ballada utca,Ballagi-tó sor,Baltacin utca,Bálvány utca,Banán utca,Bánk bán utca,Bánomkert sor,Bánya utca,Barack utca,Barátság utca,Barát utca,Barázda utca,Barcsay Károly utca,Bárka utca,Barna utca,Baross László utca,Bársonykerep utca,Bártfai utca,Bartucz Lajos utca,Basahíd utca,Bástya sor,Batthyány utca,Bazsalikom utca,Becsei utca,Bécsi körút,Béke utca,Béla utca,Belvárosi híd,Belvíz utca,Bem utca,Bence utca,Bencfahát utca,Benczúr Gyula utca,Bercsényi utca,Beregi sor,Berettyó utca,Beretzk Péter utca,Berkenye utca,Bérkert utca,Berlini körút,Bertalan híd,Bertalan utca,Berzsenyi utca,Beszterce utca,Bethlen Gábor utca,Bíbic utca,Bibó István utca,Bihari utca,Bimbó utca,Birkózó köz,Birs utca,Bite Pál utca,Blaha Lujza utca,Bocskai utca,Boda Domokos utca,Bódi Vera utca,Bodobács utca,Bódogh János utca,Bodomi út,Bodzafa utca,Boglárka utca,Bognár utca,Bojtorján utca,Bokor utca,Bokréta utca,Bölcsőde utca,Bölcs utca,Boldizsár utca,Boldogasszony sugárút,Boldogasszony utca,Bolyai János utca,Bolygó utca,Borbála utca,Borbás utca,Bordányi köz,Bordányi út,Bori Mihály utca,Boróka utca,Boros József köz,Boros József utca,Borostyán utca,Borsika utca,Bors utca,Bor utca,Börzsöny utca,Boszorkánysziget utca,Botond utca,Brassói utca,Brigád köz,Bródy Mihály utca,Bronz sor,Brüsszeli körút,Búcsú sor,Budai Nagy Antal utca,Budapesti körút,Budapesti út,Budzsák,Bujdosó György utca,Bükköny utca,Bulcsú utca,Busa utca,Búza utca,Búzavirág utca,Buzogány utca,Cankó utca,Cickafark utca,Cincér utca,Cinke utca,Citromfű utca,Citrom utca,Compó utca,Csaba utca,Csáktornyai utca,Csáky József utca,Csalán utca,Csallóköz,i utca,Csalogány utca,Csanádi utca,Csantavéri utca,Csaplár Benedek utca,Csap utca,Csatár utca,Csatorna utca,Csavar sor,Csefkó Gyula utca,Cseh Imre tér,Csejtei utca,Csemegi utca,Cserebogár utca,Cserepes sor,Cserép utca,Cseresznye utca,Cserfa utca,Cserje sor,Cserje utca,Cserőke utca,Csertő utca,Cserzy Mihály utca,Csíbor utca,Csiki utca,Csillag tér,Csillag utca,Csinszka utca,Csipkebogyó utca,Csíz utca,Csobánka utca,Csókai utca,Csokonai utca,Csöndes utca,Csongor Győző utca,Csongor tér,Csongrádi sugárút,Csonka utca,Csorba utca,Csörlő utca,Cső utca,Csüdfű utca,Csuka utca,Csuma köz,Czékus utca,Czibula utca,Dália utca,Dalos utca,Damjanich utca,Dandár utca,Dáni utca,Dankó Pista utca,Darázs utca,Dárda utca,Daru utca,Datolya utca,Deák Ferenc utca,Debreceni utca,Délceg utca,Délibáb utca,Deli Károly utca,Demeter Ferenc utca,Derce utca,Deres utca,Dér István utca,Derkovits fasor,Déryné utca,Dettre János utca,Déva utca,Diadal utca,Dinnyés utca,Diófa utca,Díszlet utca,Dobogó utca,Dobó István utca,Dobos utca,Dobó utca,Dobozi utca,Dolgos utca,Domaszéki út,Dóm tér,Dongó utca,Dorogi Imre utca,Dorottya utca,Dorozsmai út,Dózsa utca,Dráva utca,Dudás utca,Duda utca,Dugonics tér,Dugonics utca,Dűlő utca,Duna utca,Ecetfa utca,Ecsedi Géza utca,Ecsetpázsit köz,Egressy Béni utca,Egres utca,Egyenlőség utca,Egyetem utca,EKO park,Előd utca,Emese utca,Eötvös utca,Eperjesi sor,Eper utca,Építő utca,Érc utca,Erdei Ferenc utca,Erdélyi tér,Erdészház utca,Erdőkerülő utca,Erdőstarcsa utca,Erdőszéli utca,Erdő utca,Erkel utca,Erős János utca,Erzsébet utca,Estike utca,Északi sor,Esze Tamás utca,Eszperantó utca,Eszter utca,Etelka sor,Eurovelo 11,Éva utca,Evező köz,Ezüstfa utca,Ezüst utca,Fácán utca,Fadrusz utca,Fagyöngy utca,Fahéj utca,Fakopáncs utca,Faragó dűlő,Faragó utca,Farkas utca,Fátyolka utca,Fátyolvirág köz,Fecskefű köz,Fecske utca,Fehérpart utca,Fehértó utca,Feketeföld utca,Feketesas utca,Felebarát köz,Felhő utca,Felső kikötő sor,Felsőnyomás út,Felső Tisza part,Fél utca,Fenyveslejtő sor,Fenyves utca,Festő utca,Fésű utca,Fiala Antal utca,Fiume utca,Flóra utca,Fő fasor,Fogarasi utca,Fogas utca,Foka,Földmíves utca,Föld utca,Földváry utca,Fölszél utca,Föltámadás utca,Fonógyári út,Fontos Sándor köz,Fontos Sándor utca,Forradalom utca,Forrai utca,Fő tér,Fővám köz,Fraknói utca,Francia utca,Füge sor,Fülemüle utca,Füredi utca,Fűrész utca,Fürj utca,Fürkész utca,Fürt utca,Fűtőház köz,Fűtőmű utca,Futrinka utca,Füvészkerti út,Füvészkert sor,Füzény köz,Füzértekercs utca,Füzér utca,Füzes utca,Füzike köz,Gábor Áron utca,Gádor köz,Galagonya utca,Galamb utca,Galgóci utca,Gallé László utca,Gál utca,Garam utca,Gárdonyi Géza utca,Gáspár Zoltán utca,Gát utca,Gáz utca,Gébics utca,Gelei József utca,Gémorr köz,Gém utca,Gép utca,Gera Sándor utca,Gergely köz,Gerle utca,Gesztenye utca,Gizella utca,Gogol utca,Gólyahír utca,Gólya utca,Gomba utca,Gombkötő utca,Gömöri utca,Göncz Árpád sétány,Göndör sor,Gorkij utca,Gőzmalom utca,Gőz utca,Gránit sor,Gulácsi park,Gutenberg utca,Gyálai út,Gyálaréti út,Gyála széle utca,Gyalu utca,Gyár utca,Gyékényesi út,Gyémánt utca,Gyergyói utca,Gyertyámos utca,Gyertyaöntő utca,Gyevi utca,Gyík utca,Gyimesi utca,Gyömbér utca,Gyöngyköles utca,Gyöngyöspata utca,Gyöngytyúk utca,Gyöngyvirág utca,Gyöp sor,Gyula utca,Gyümölcs utca,Gyuris utca,Gyűszűvirág utca,Hajdú utca,Hajlat utca,Hajnalka utca,Hajnal utca,Hajnóczy utca,Hajós utca,Haladás utca,Halas utca,Háló utca,Hambár út,Hám utca,Hangos utca,Hangya utca,Harangláb utca,Harangvirág utca,Harcos sor,Harcos utca,Harcsa utca,Hargitai utca,Harmat utca,Hársfa sétány,Hársfa utca,Hasító utca,Határőr utca,Hátszegi utca,Hattyas utca,Hattyú utca,Hegedű utca,Hegyközség utca,Héja utca,Heller köz,Herke utca,Hernyós utca,Hetényi Géza utca,Hétvezér utca,Híd utca,Hídverő utca,Hild kapu,Hiúz utca,Hóbiárt basa utca,Hold utca,Holló utca,Holt-Maros sétány,Holt-Tisza sor,Homok utca,Homonnai utca,Homoródi utca,Honfoglalás utca,Hont Ferenc utca,Hópárduc utca,Horgony utca,Horgosi utca,Horváth Mihály utca,Hősök tere,Hosszútöltés utca,Hosszú utca,Huba utca,Hullám utca,Hunyadi tér,Huszár Mátyás rakpart,Huszár utca,Huszka Jenő utca,Hüvelyk utca,Hűvös köz,Ibolya utca,Iglói utca,Ikarusz köz,Iker utca,Ikon sor,Ildikó utca,Ilona utca,Ilosvai utca,Imre utca,Indóház tér,Ínfű utca,Ingovány utca,Ipoly sor,Iringó utca,Irinyi János utca,Iskola utca,István utca,Ivánovics György utca,Izabella híd,Izabella utca,Izsóp utca,Jácint utca,Jakab Lajos utca,Jancsó Miklós utca,Jankovich utca,János-ér út,Jász utca,Jávorka utca,Jázmin utca,Jerney utca,Jobb fasor,Jókai utca,Jolánka utca,Jósika utca,József Attila sugárút,Judit utca,Juharfás utca,Juhász Gyula utca,Júlia utca,Kabóca utca,Kácsa utca,Kadarka utca,Káka utca,Kakukkfű utca,Kakukk utca,Kalász utca,Kállay Albert utca,Kálmán köz,Kálmány Lajos utca,Kálvária sugárút,Kálvária tér,Kálvin tér,Kamarási utca,Kamaratöltés,Kamilla utca,Kandó Kálmán utca,Kanizsai utca,Kankalin utca,Kántor utca,Kapás utca,Kapisztrán út,Kapitány utca,Kápolna utca,Kapor utca,Kapu köz,Karánsebesi utca,Kárász utca,Károlyi utca,Kassai utca,Kassák utca,Kaszás utca,Katalin utca,Katáng utca,Kátay utca,Katica utca,Katona József utca,Kavics utca,Kazinczy utca,Kece utca,Kecsege utca,Kecskeméti utca,Kékfestő utca,Kékperje utca,Kék utca,Kelemen László utca,Keleti út,Kemes utca,Kendergyári utca,Kenguru köz,Kenyérgyári út,Kenyérvári sor,Kénytelen sor,Kerékgyártó utca,Kereskedő köz,Kereszttöltés utca,Kereszt utca,Kérész utca,Kertész utca,Késmárki utca,Keszeg utca,Kétérköz utca,Kettőshatári út,Kézdi utca,Kígyószisz utca,Kígyó utca,Kikindai utca,Kikirics utca,Kikötő sor,Kinizsi Pál utca,Kisbaktói út,Kisbogáros utca,Kiserdő sor,Kisfaludy utca,Kiskert utca,Kis köz,Kismartoni utca,Kiss Ernő utca,Kiss Ferenc utca,Kiss Menyhért utca,Kisszőlő utca,Kisteleki Ede utca,Kisteleki út,Kis-Tisza utca,Kisvasút sor,Kivi utca,Klapka tér,Klára utca,Klauzál tér,Kőbárány utca,Kockaház utca,Kokárda utca,Kökény utca,Kökörcsin utca,Kókusz utca,Kölcsey tér,Kölcsey utca,Kollégiumi út,Koloszár udvar,Kolozsvári tér,Költő utca,Kombinát köz,Kömény utca,Kond utca,Könyves Kálmán köz,Koppány köz,Korányi fasor,Korda utca,Kormányos utca,Körömvirág utca,Korondi utca,Kőrösmező utca,Kőrös sor,Körte utca,Körtöltés,Körtöltés utca,Kosbor köz,Kossuth Lajos sugárút,Kossuth utca,Koszorú utca,Kovács udvar,Kövidinka utca,Közép fasor,Közép-kapu utca,Közép kikötő sor,Kristály utca,Krúdy Gyula utca,Kubikos utca,Kukorica utca,Kukovetz Nana utca,Küküllői utca,Külüs köz,Kundombi utca,Kun utca,Kürt utca,Kuruc utca,Kurucvölgyi út,Kürü sor,Kút utca,Ladvánszky utca,Lajta utca,Laktanya utca,Láma utca,Láng Imre utca,Lant utca,Lányi Béla utca,Láp utca,Laura utca,Leányszállás köz,Lechner tér,Léda utca,Légió utca,Legyezőfű köz,Lehel utca,Lékai utca,Lendvai utca,Lengyel udvar,Lengyel utca,Lenkey utca,Lepke utca,Levél utca,Levendula utca,Lidicei tér,Liga utca,Liget sor,Lile utca,Liliom köz,Liliom utca,Lilla utca,Limány köz,Liszt Ferenc sétány,Liszt utca,Lizinka köz,Lőcsei utca,Lomb utca,Lomnici utca,Londoni körút,Lövölde utca,Lőwy Sándor utca,Lúdvári utca,Lugas utca,Mácsonya utca,Madách utca,Madarász utca,Magas utca,Magdolna utca,Máglya sor,Magtár köz,Magyar utca,Majális utca,Majdáni sor,Major utca,Május 1. utca,Makai út,Makkoserdő sor,Makkosházi körút,Málna utca,Malom utca,Mályvarózsa utca,Mályva utca,Mandarin utca,Mandula utca,Máramarosi utca,Margaréta utca,Margit utca,Mária utca,Markovits Iván utca,Márna utca,Maróczy Géza tér,Marostői utca,Marostorok utca,Maros utca,Maróthy Gergely tér,Maróti utca,Mars tér,Márták dűlő,Martonosi utca,Márvány utca,Máté utca,Mátra köz,Matty tér,Mátyás király tér,Mátyás király utca,Matyparti utca,MÁV utca,Mayer Miklós utca,Mazsola utca,Medveszőlő utca,Meggyfa utca,Méh utca,Melinda utca,Menhely utca,Menta utca,Mérey utca,Mertz Tibor utca,Mester utca,Metro park,oló,Mező utca,Mikes Kelemen utca,Miklós utca,Mikszáth Kálmán utca,Mimóza utca,Mogyoró utca,Moholi utca,Mokrini utca,Molnár utca,Móra Ferenc híd,Mórahegyi út,Móra utca,Móravárosi körút,Móricz Zsigmond utca,Moszkvai körút,Mozdony utca,Műhely utca,Munkácsy utca,Munkás köz,Munkás utca,Murányi utca,Mura utca,Muskátli utca,Muskó köz,Muskotály utca,Muslinca utca,Mustár utca,Must utca,Műves út,Nadályfű utca,Nádas utca,Nádor utca,Nagybaktói út,Nagybecskereki utca,Nagybercsényi utca,Nagy Jenő utca,Nagykikinda utca,Nagyrét utca,Nagyszeg utca,Nagyszéki út,Nagyszombati utca,Napfény köz,Napos út,Napraforgó utca,Napsugár utca,Nap utca,Narancs utca,Naspolya utca,Nefelejcs utca,Négyház utca,Negyvennyolcas utca,Nemes takács utca,Németh András utca,Nemzetőr sor,Népdal utca,Népkert sor,Nőszőfű utca,Nyárfa utca,Nyár köz,Nyilassy utca,Nyíl utca,Nyírfa utca,Nyitra utca,Nyugati sor,Óbébai utca,Ocskó utca,Ökörszem utca,Október 6. utca,Olajos utca,Oldal utca,Olt utca,Oltványi utca,Orczy István utca,Öreghegy dűlő,Öreghegyi utca,Orgona utca,Őrlő köz,Oroszlán utca,Orsolya utca,Orsovai utca,Ortutay utca,Örvény utca,Orvos köz,Oskola utca,Ostrom utca,Őszibarack utca,Osztrovszky utca,Ősz utca,Öthalom utca,Ötház utca,Otthon utca,Óvoda utca,Pacsirta utca,Pajtás utca,Palackozó utca,Palánk,Palánkai utca,Palánta utca,Pálfy utca,Palics köz,Pálma utca,Palóc utca,Pál utca,Pálya tér,Páncél köz,Pancsovai utca,Panda tér,Pápai utca,Paprika utca,Párizsi körút,Párlófű utca,Parobek Alajos utca,Passzázs sor,Pasztinák köz,Pásztortáska köz,Pásztor utca,Pázsit utca,Pécskai utca,Pentelei sor,Petneházy utca,Petőfi Sándor sugárút,Petőfi utca,Petresi utca,Petrozsényi utca,Pihenő utca,Pilisi utca,Pillangó utca,Pille utca,Pillich Kálmán utca,Pimpó utca,Pintér József utca,Pinty utca,Pipacs utca,Pipiske utca,Pipitér utca,Piroska tér,Piszke utca,Pisztácia utca,Pitypang utca,Pók utca,Ponty utca,Postás utca,Pöstyéni utca,Pósz Jenő utca,Pozsonyi Ignác utca,Pulz utca,Puskás utca,Püspök utca,Pusztaszeri utca,Rába utca,Rábéi utca,Radnóti utca,Rahói utca,Rákóczi utca,Raktár köz,Rebarbara utca,Réce utca,Régész tér,Regina utca,Régiposta utca,Reizner János utca,Rekettye utca,Remény utca,Remete utca,Rendező tér,Rengey utca,Répás utca,Rerrich Béla tér,Retek utca,Réti utca,Révai utca,Rév utca,Rezeda utca,Rezgőfű köz,Rézöntő utca,Réz utca,Ribizli utca,Rigómező utca,Rigó utca,Ringló utca,Rohonci utca,Rókusi körút,Római körút,Rom utca,Róna utca,Roosevelt tér,Rosta köz,Röszkei utca,Rövid köz,Rövid utca,Rozmaring utca,Rózsaszéki utca,Rózsatő utca,Rózsa utca,Rozsnok utca,Rozsnyói utca,Rügy utca,Ruszti utca,Sáfrány utca,Sajka utca,Sándor utca,Sarkantyú utca,Sárkány utca,Sarlófű utca,Sarló utca,Sárosi utca,Sas utca,Sás utca,Selmeci utca,Selyem utca,Semmelweis utca,Sepsi utca,Seres János utca,Siha köz,Sikér köz,Sík Sándor utca,Sínpár sor,Sípos Iván utca,Sirály utca,Sóhordó utca,Sólya utca,Sólyom utca,Sömlyék út,Somogyi utca,Som utca,Sőtér István köz,Só utca,Sportpálya út,StefániaStrand utca,Subasa út,Sügér utca,Süllő utca,Sulyom út,Süveg utca,Szabadkai út,Szabadság tér,Szabad sajtó utca,Szabó János utca,Szajáni utca,Szakolcai utca,Szák út,Szalmáskert út,Szamóca utca,Szamos utca,Szántó Kovács János utca,Szántó utca,Szappanos utca,Szarkaláb utca,Szarvas köz,Szatymazi utca,Száva utca,Széchenyi István utca,Széchenyi tér,Szécsi utca,Szeder utca,Szegedi pihenőhely,Szegfű utca,Székely sor,Szekerce utca,Szekeres utca,Széksósi út,Szék utca,Szellő utca,Szélmalom utca,Szélső sor,Szél utca,Széna utca,Szende Béla utca,Szendrey Júlia utca,Szent Antal utca,Szent Ferenc utca,Szent Gellért utca,Szent-Györgyi Albert utca,Szent György tér,Szentháromság utca,Szent István tér,Szent János tér,Szent László utca,Szentmihályteleki utca,Szent Mihály utca,Szent Miklós utca,Szent Rókus tér,Szepesi utca,Szerb utca,Szercsika utca,Szérűskerti sor,Szérűskert utca,Szigeti út,Sziget utca,Szigony utca,Szikla utca,Szilágyi utca,Sziliszék út,Szilléri sor,Szilléri sugárút,Szilva utca,Szirom utca,Szitakötő utca,Szivárvány utca,Szív utca,Szívvirág utca,Szöcske utca,Szögi József utca,Szőkefalvi-Nagy Béla utca,Szőke Tisza utca,Szőke utca,Szolgáltató sor,Szőlő utca,Szondi György utca,Szőregi út,Szöri utca,Szövetkezeti út,Szövetség utca,Szövő utca,Sztriha Kálmán utca,Szűcs utca,Szúnyog utca,Szurokfű utca,Tabán utca,Tábornok utca,Tábor utca,Takaréktár utca,Taksony utca,Talicska utca,Talpas utca,Tambura utca,Tanács utca,Táncsics Mihály utca,Tanító tér,Tápai utca,Tápé széle,Tapodi utca,Tapolcsányi utca,Tarján széle,Tárkony utca,Tarló utca,Tarnóci utca,Tárnokfű utca,Tárogató utca,Tas utca,Tátra tér,Tavasz utca,Távol utca,Téglagyár utca,Tégla köz,Téglaverő utca,Tegzes utca,Teleki utca,Temesvári körút,Temesvári utca,Temető utca,Templom tér,Tenkes köz,Terehalmi út,Teréz utca,Termelő utca,Testvériség köz,Teve utca,Textilgyári út,Thököly utca,Tigér utca,Tigris utca,Tímár utca,Tinódi utca,Tisza köz,Tisza Lajos körút,Tisza Lajos utca,Tisza töltés,Tiszavirág utca,Titeli utca,Tizenhetedik út,Tóbiás György utca,Toboz utca,Toldy utca,Tölgyes utca,Tölgyfa utca,Töltés utca,Tömörkény utca,Tompai kapu út,Tompa Mihály utca,Tópart utca,Topolya sor,Tordai utca,Torma utca,Torockói utca,Törökkanizsa utca,Török utca,Törökverő utca,Torontál tér,Törő utca,Tóth János dűlő,Tó utca,Tőzike utca,Trafik utca,Traktor utca,Trencséni utca,Trombita utca,Tücsök utca,Tulipán utca,Tündér utca,Tünde tér,Turbolya utca,Turista utca,Turul utca,Tüsök utca,Tüzép köz,Túzok utca,Tűzoltó utca,Udvardi János utca,Udvarhelyi utca,Ugar utca,Új Élet utca,Újföld sor,Újhelyi köz,Ujjaskosbor utca,Új tér,Újvárosi utca,Újvidéki utca,Újvilág utca,Ungvári utca,Űrhajós utca,Üröm utca,Üstökös utca,Úszó út,Útifű utca,Uzsoki utca,Vadalma utca,Vadas Márton utca,Vadászház dűlő,Vadász utca,Vadkerti tér,Vadliba utca,Vadmacska utca,Vadmurok utca,Vadrózsa sor,Vágány utca,Vágóhíd utca,Vágóhorog utca,Vág utca,Vajda utca,Vajk utca,Vak Bottyán utca,Váltó utca,Vályog köz,Vályogos utca,Vám tér,Vándor köz,Vándor utca,Vánky József utca,Váradi utca,Varga utca,Városgazda sor,Varsa utca,Vártó utca,Vár utca,Vásárhelyi Pál utca,Vásártér sor,Vásár utca,Vasas Szent Péter utca,Vasfű utca,Vasgyár utca,Vaskapu utca,Vaspálya utca,Vasutas sor,Vas utca,Vasúti rakodó,Vasvári Pál utca,Vaszy Viktor tér,Védőnő utca,Vedres utca,Végvári utca,Vellay Imre utca,Venyige utca,Véradó utca,Verbéna utca,Vércse utca,Verecke utca,Veres ács utca,Vereshomok dűlő,Vereshomok út,Veres Péter utca,Verseci utca,Verseny utca,Vértói út,Vezér utca,Victor Hugo utca,Vidra utca,Vikunya utca,Világos utca,Vincellér utca,Vinkler László út,Viola utca,Virág utca,Vitéz köz,Vitéz utca,Vitorla utca,Vívó köz,Viza utca,Vízipók utca,Víztorony tér,Vlasics Károly utca,Vöcsök utca,Völgyérhát utca,Vörösmarty utca,Wagner Viktória utca,Wallisch Kálmán utca,Wesselényi utca,Wimmer Fülöp utca,Ybl Miklós utca,Zádori utca,Zágon utca,Zágráb utca,Zákány utca,Zalán utca,Zápor út,Zárda utca,Zárt utca,Zászló utca,Zátony utca,Zengő utca,Zentai utca,Zocskár udvar,Zöldfási út,Zöldfa utca,Zoltánfy István utca,Zoltán utca,Zólyomi utca,Zombori utca,Zrínyi utca,Zsák köz,Zsálya utca,Zsámbokréti sor,Zsilip utca,Zsil utca,Zsitva sor,Zsoldos köz,Zsolnai utca,Zsombói út,Zsombolyai utca,Zsótér utca,Zsukov tér,Zsurló utca,Anna-kút,Árpád tér,Csongor tér,Dóm tér,Dugonics tér,Eötvös utca"
export const szegedStreetsArray = [] = streetString.split(',');

// export const szegedStreetsObject = {};
export const szegedStreetsObject = {
  '10. utca': null,
  '11. utca': null,
  '12. utca': null,
  '13. utca': null,
  '14. utca': null,
  '15. utca': null,
  '16. utca': null,
  '17. utca': null,
  '18. utca': null,
  '19. utca': null,
  '1. utca': null,
  '20. utca': null,
  '21. utca': null,
  '22. utca': null,
  '23. utca': null,
  '24. utca': null,
  '25. utca': null,
  '26. utca': null,
  '27. utca': null,
  '28. utca': null,
  '29. utca': null,
  '2. utca': null,
  '30. utca': null,
  '31. utca': null,
  '32. utca': null,
  '33. utca': null,
  '34. utca': null,
  '35. utca': null,
  '36. utca': null,
  '37. utca': null,
  '38. utca': null,
  '39. utca': null,
  '3. utca': null,
  '40. utca': null,
  '41. utca': null,
  '42. utca': null,
  '43. utca': null,
  '44. utca': null,
  '45. utca': null,
  '46. utca': null,
  '47. utca': null,
  '48. utca': null,
  '49. utca': null,
  '4. utca': null,
  '50. utca': null,
  '51. utca': null,
  '52. utca': null,
  '53. utca': null,
  '54. utca': null,
  '55. utca': null,
  '57. utca': null,
  '58. utca': null,
  '59. utca': null,
  '5. utca': null,
  '60. utca': null,
  '6. utca': null,
  '7. utca': null,
  '8. utca': null,
  '9. utca': null,
  'Aba utca': null,
  'Ábel utca': null,
  'Abony utca': null,
  'Acél utca': null,
  'Acsalapu utca': null,
  'Ács utca': null,
  'Adai utca': null,
  'Ádám utca': null,
  'Adél köz': null,
  'Adorján utca': null,
  'Ady tér': null,
  'Áfonya utca': null,
  'Aggófű utca': null,
  'Ágnes utca': null,
  'Ág utca': null,
  'Agyagos utca': null,
  'Ajtony köz': null,
  'Akácfa utca': null,
  'Akácos utca': null,
  'Ákos utca': null,
  'Alföldi utca': null,
  'Algyői út': null,
  'Alig utca': null,
  'Alkony utca': null,
  'Alkotmány utca': null,
  'Állomás utca': null,
  'Alma utca': null,
  'Álmos köz': null,
  'Alsó kikötő sor': null,
  'Alsó-nyomási sor': null,
  'Ambrus utca': null,
  'Ámika utca': null,
  'Ananász utca': null,
  'András utca': null,
  'Ánizs utca': null,
  'Anna utca': null,
  'Apáca utca': null,
  'Apály utca': null,
  'Apáthy István utca': null,
  'Apatini utca': null,
  'Apátság utca': null,
  'Aradi vértanúk tere': null,
  'Aranka utca': null,
  'Arany János utca': null,
  'Aranyműves köz': null,
  'Aranyosi utca': null,
  'Araszt utca': null,
  'Arató utca': null,
  'Árbóc utca': null,
  'Árnika utca': null,
  'Árnyas utca': null,
  'Árok utca': null,
  'Árpád tér': null,
  'Árpa utca': null,
  'Árvacsalán köz': null,
  'Árvácska utca': null,
  'Árvalányhaj utca': null,
  'Árva utca': null,
  'Árvíz utca': null,
  'Ásványhát utca': null,
  'Aszat köz': null,
  'Asztalos utca': null,
  'Atracél köz': null,
  'Átrium köz': null,
  'Attila utca': null,
  'Avar utca': null,
  'Babér utca': null,
  'Babits Mihály utca': null,
  'Back Bernát utca': null,
  'Bacsó Béla utca': null,
  'Bagoly utca': null,
  'Bajai út': null,
  'Bajmóci utca': null,
  'Bajnok utca': null,
  'Bajza utca': null,
  'Bakay Nándor utca': null,
  'Bakonyi utca': null,
  'Baktói utca': null,
  'Balabás utca': null,
  'Balajthy utca': null,
  'Balatoni utca': null,
  'Balázs Béla utca': null,
  'Bal fasor': null,
  'Bálint Sándor utca': null,
  'Ballada utca': null,
  'Ballagi-tó sor': null,
  'Baltacin utca': null,
  'Bálvány utca': null,
  'Banán utca': null,
  'Bánk bán utca': null,
  'Bánomkert sor': null,
  'Bánya utca': null,
  'Barack utca': null,
  'Barátság utca': null,
  'Barát utca': null,
  'Barázda utca': null,
  'Barcsay Károly utca': null,
  'Bárka utca': null,
  'Barna utca': null,
  'Baross László utca': null,
  'Bársonykerep utca': null,
  'Bártfai utca': null,
  'Bartucz Lajos utca': null,
  'Basahíd utca': null,
  'Bástya sor': null,
  'Batthyány utca': null,
  'Bazsalikom utca': null,
  'Becsei utca': null,
  'Bécsi körút': null,
  'Béke utca': null,
  'Béla utca': null,
  'Belvárosi híd': null,
  'Belvíz utca': null,
  'Bem utca': null,
  'Bence utca': null,
  'Bencfahát utca': null,
  'Benczúr Gyula utca': null,
  'Bercsényi utca': null,
  'Beregi sor': null,
  'Berettyó utca': null,
  'Beretzk Péter utca': null,
  'Berkenye utca': null,
  'Bérkert utca': null,
  'Berlini körút': null,
  'Bertalan híd': null,
  'Bertalan utca': null,
  'Berzsenyi utca': null,
  'Beszterce utca': null,
  'Bethlen Gábor utca': null,
  'Bíbic utca': null,
  'Bibó István utca': null,
  'Bihari utca': null,
  'Bimbó utca': null,
  'Birkózó köz': null,
  'Birs utca': null,
  'Bite Pál utca': null,
  'Blaha Lujza utca': null,
  'Bocskai utca': null,
  'Boda Domokos utca': null,
  'Bódi Vera utca': null,
  'Bodobács utca': null,
  'Bódogh János utca': null,
  'Bodomi út': null,
  'Bodzafa utca': null,
  'Boglárka utca': null,
  'Bognár utca': null,
  'Bojtorján utca': null,
  'Bokor utca': null,
  'Bokréta utca': null,
  'Bölcsőde utca': null,
  'Bölcs utca': null,
  'Boldizsár utca': null,
  'Boldogasszony sugárút': null,
  'Boldogasszony utca': null,
  'Bolyai János utca': null,
  'Bolygó utca': null,
  'Borbála utca': null,
  'Borbás utca': null,
  'Bordányi köz': null,
  'Bordányi út': null,
  'Bori Mihály utca': null,
  'Boróka utca': null,
  'Boros József köz': null,
  'Boros József utca': null,
  'Borostyán utca': null,
  'Borsika utca': null,
  'Bors utca': null,
  'Bor utca': null,
  'Börzsöny utca': null,
  'Boszorkánysziget utca': null,
  'Botond utca': null,
  'Brassói utca': null,
  'Brigád köz': null,
  'Bródy Mihály utca': null,
  'Bronz sor': null,
  'Brüsszeli körút': null,
  'Búcsú sor': null,
  'Budai Nagy Antal utca': null,
  'Budapesti körút': null,
  'Budapesti út': null,
  'Budzsák': null,
  'Bujdosó György utca': null,
  'Bükköny utca': null,
  'Bulcsú utca': null,
  'Busa utca': null,
  'Búza utca': null,
  'Búzavirág utca': null,
  'Buzogány utca': null,
  'Cankó utca': null,
  'Cickafark utca': null,
  'Cincér utca': null,
  'Cinke utca': null,
  'Citromfű utca': null,
  'Citrom utca': null,
  'Compó utca': null,
  'Csaba utca': null,
  'Csáktornyai utca': null,
  'Csáky József utca': null,
  'Csalán utca': null,
  'Csallóköz': null,
  'i utca': null,
  'Csalogány utca': null,
  'Csanádi utca': null,
  'Csantavéri utca': null,
  'Csaplár Benedek utca': null,
  'Csap utca': null,
  'Csatár utca': null,
  'Csatorna utca': null,
  'Csavar sor': null,
  'Csefkó Gyula utca': null,
  'Cseh Imre tér': null,
  'Csejtei utca': null,
  'Csemegi utca': null,
  'Cserebogár utca': null,
  'Cserepes sor': null,
  'Cserép utca': null,
  'Cseresznye utca': null,
  'Cserfa utca': null,
  'Cserje sor': null,
  'Cserje utca': null,
  'Cserőke utca': null,
  'Csertő utca': null,
  'Cserzy Mihály utca': null,
  'Csíbor utca': null,
  'Csiki utca': null,
  'Csillag tér': null,
  'Csillag utca': null,
  'Csinszka utca': null,
  'Csipkebogyó utca': null,
  'Csíz utca': null,
  'Csobánka utca': null,
  'Csókai utca': null,
  'Csokonai utca': null,
  'Csöndes utca': null,
  'Csongor Győző utca': null,
  'Csongor tér': null,
  'Csongrádi sugárút': null,
  'Csonka utca': null,
  'Csorba utca': null,
  'Csörlő utca': null,
  'Cső utca': null,
  'Csüdfű utca': null,
  'Csuka utca': null,
  'Csuma köz': null,
  'Czékus utca': null,
  'Czibula utca': null,
  'Dália utca': null,
  'Dalos utca': null,
  'Damjanich utca': null,
  'Dandár utca': null,
  'Dáni utca': null,
  'Dankó Pista utca': null,
  'Darázs utca': null,
  'Dárda utca': null,
  'Daru utca': null,
  'Datolya utca': null,
  'Deák Ferenc utca': null,
  'Debreceni utca': null,
  'Délceg utca': null,
  'Délibáb utca': null,
  'Deli Károly utca': null,
  'Demeter Ferenc utca': null,
  'Derce utca': null,
  'Deres utca': null,
  'Dér István utca': null,
  'Derkovits fasor': null,
  'Déryné utca': null,
  'Dettre János utca': null,
  'Déva utca': null,
  'Diadal utca': null,
  'Dinnyés utca': null,
  'Diófa utca': null,
  'Díszlet utca': null,
  'Dobogó utca': null,
  'Dobó István utca': null,
  'Dobos utca': null,
  'Dobó utca': null,
  'Dobozi utca': null,
  'Dolgos utca': null,
  'Domaszéki út': null,
  'Dóm tér': null,
  'Dongó utca': null,
  'Dorogi Imre utca': null,
  'Dorottya utca': null,
  'Dorozsmai út': null,
  'Dózsa utca': null,
  'Dráva utca': null,
  'Dudás utca': null,
  'Duda utca': null,
  'Dugonics tér': null,
  'Dugonics utca': null,
  'Dűlő utca': null,
  'Duna utca': null,
  'Ecetfa utca': null,
  'Ecsedi Géza utca': null,
  'Ecsetpázsit köz': null,
  'Egressy Béni utca': null,
  'Egres utca': null,
  'Egyenlőség utca': null,
  'Egyetem utca': null,
  'EKO park': null,
  'Előd utca': null,
  'Emese utca': null,
  'Eötvös utca': null,
  'Eperjesi sor': null,
  'Eper utca': null,
  'Építő utca': null,
  'Érc utca': null,
  'Erdei Ferenc utca': null,
  'Erdélyi tér': null,
  'Erdészház utca': null,
  'Erdőkerülő utca': null,
  'Erdőstarcsa utca': null,
  'Erdőszéli utca': null,
  'Erdő utca': null,
  'Erkel utca': null,
  'Erős János utca': null,
  'Erzsébet utca': null,
  'Estike utca': null,
  'Északi sor': null,
  'Esze Tamás utca': null,
  'Eszperantó utca': null,
  'Eszter utca': null,
  'Etelka sor': null,
  'Eurovelo 11': null,
  'Éva utca': null,
  'Evező köz': null,
  'Ezüstfa utca': null,
  'Ezüst utca': null,
  'Fácán utca': null,
  'Fadrusz utca': null,
  'Fagyöngy utca': null,
  'Fahéj utca': null,
  'Fakopáncs utca': null,
  'Faragó dűlő': null,
  'Faragó utca': null,
  'Farkas utca': null,
  'Fátyolka utca': null,
  'Fátyolvirág köz': null,
  'Fecskefű köz': null,
  'Fecske utca': null,
  'Fehérpart utca': null,
  'Fehértó utca': null,
  'Feketeföld utca': null,
  'Feketesas utca': null,
  'Felebarát köz': null,
  'Felhő utca': null,
  'Felső kikötő sor': null,
  'Felsőnyomás út': null,
  'Felső Tisza part': null,
  'Fél utca': null,
  'Fenyveslejtő sor': null,
  'Fenyves utca': null,
  'Festő utca': null,
  'Fésű utca': null,
  'Fiala Antal utca': null,
  'Fiume utca': null,
  'Flóra utca': null,
  'Fő fasor': null,
  'Fogarasi utca': null,
  'Fogas utca': null,
  'Foka': null,
  'Földmíves utca': null,
  'Föld utca': null,
  'Földváry utca': null,
  'Fölszél utca': null,
  'Föltámadás utca': null,
  'Fonógyári út': null,
  'Fontos Sándor köz': null,
  'Fontos Sándor utca': null,
  'Forradalom utca': null,
  'Forrai utca': null,
  'Fő tér': null,
  'Fővám köz': null,
  'Fraknói utca': null,
  'Francia utca': null,
  'Füge sor': null,
  'Fülemüle utca': null,
  'Füredi utca': null,
  'Fűrész utca': null,
  'Fürj utca': null,
  'Fürkész utca': null,
  'Fürt utca': null,
  'Fűtőház köz': null,
  'Fűtőmű utca': null,
  'Futrinka utca': null,
  'Füvészkerti út': null,
  'Füvészkert sor': null,
  'Füzény köz': null,
  'Füzértekercs utca': null,
  'Füzér utca': null,
  'Füzes utca': null,
  'Füzike köz': null,
  'Gábor Áron utca': null,
  'Gádor köz': null,
  'Galagonya utca': null,
  'Galamb utca': null,
  'Galgóci utca': null,
  'Gallé László utca': null,
  'Gál utca': null,
  'Garam utca': null,
  'Gárdonyi Géza utca': null,
  'Gáspár Zoltán utca': null,
  'Gát utca': null,
  'Gáz utca': null,
  'Gébics utca': null,
  'Gelei József utca': null,
  'Gémorr köz': null,
  'Gém utca': null,
  'Gép utca': null,
  'Gera Sándor utca': null,
  'Gergely köz': null,
  'Gerle utca': null,
  'Gesztenye utca': null,
  'Gizella utca': null,
  'Gogol utca': null,
  'Gólyahír utca': null,
  'Gólya utca': null,
  'Gomba utca': null,
  'Gombkötő utca': null,
  'Gömöri utca': null,
  'Göncz Árpád sétány': null,
  'Göndör sor': null,
  'Gorkij utca': null,
  'Gőzmalom utca': null,
  'Gőz utca': null,
  'Gránit sor': null,
  'Gulácsi park': null,
  'Gutenberg utca': null,
  'Gyálai út': null,
  'Gyálaréti út': null,
  'Gyála széle utca': null,
  'Gyalu utca': null,
  'Gyár utca': null,
  'Gyékényesi út': null,
  'Gyémánt utca': null,
  'Gyergyói utca': null,
  'Gyertyámos utca': null,
  'Gyertyaöntő utca': null,
  'Gyevi utca': null,
  'Gyík utca': null,
  'Gyimesi utca': null,
  'Gyömbér utca': null,
  'Gyöngyköles utca': null,
  'Gyöngyöspata utca': null,
  'Gyöngytyúk utca': null,
  'Gyöngyvirág utca': null,
  'Gyöp sor': null,
  'Gyula utca': null,
  'Gyümölcs utca': null,
  'Gyuris utca': null,
  'Gyűszűvirág utca': null,
  'Hajdú utca': null,
  'Hajlat utca': null,
  'Hajnalka utca': null,
  'Hajnal utca': null,
  'Hajnóczy utca': null,
  'Hajós utca': null,
  'Haladás utca': null,
  'Halas utca': null,
  'Háló utca': null,
  'Hambár út': null,
  'Hám utca': null,
  'Hangos utca': null,
  'Hangya utca': null,
  'Harangláb utca': null,
  'Harangvirág utca': null,
  'Harcos sor': null,
  'Harcos utca': null,
  'Harcsa utca': null,
  'Hargitai utca': null,
  'Harmat utca': null,
  'Hársfa sétány': null,
  'Hársfa utca': null,
  'Hasító utca': null,
  'Határőr utca': null,
  'Hátszegi utca': null,
  'Hattyas utca': null,
  'Hattyú utca': null,
  'Hegedű utca': null,
  'Hegyközség utca': null,
  'Héja utca': null,
  'Heller köz': null,
  'Herke utca': null,
  'Hernyós utca': null,
  'Hetényi Géza utca': null,
  'Hétvezér utca': null,
  'Híd utca': null,
  'Hídverő utca': null,
  'Hild kapu': null,
  'Hiúz utca': null,
  'Hóbiárt basa utca': null,
  'Hold utca': null,
  'Holló utca': null,
  'Holt-Maros sétány': null,
  'Holt-Tisza sor': null,
  'Homok utca': null,
  'Homonnai utca': null,
  'Homoródi utca': null,
  'Honfoglalás utca': null,
  'Hont Ferenc utca': null,
  'Hópárduc utca': null,
  'Horgony utca': null,
  'Horgosi utca': null,
  'Horváth Mihály utca': null,
  'Hősök tere': null,
  'Hosszútöltés utca': null,
  'Hosszú utca': null,
  'Huba utca': null,
  'Hullám utca': null,
  'Hunyadi tér': null,
  'Huszár Mátyás rakpart': null,
  'Huszár utca': null,
  'Huszka Jenő utca': null,
  'Hüvelyk utca': null,
  'Hűvös köz': null,
  'Ibolya utca': null,
  'Iglói utca': null,
  'Ikarusz köz': null,
  'Iker utca': null,
  'Ikon sor': null,
  'Ildikó utca': null,
  'Ilona utca': null,
  'Ilosvai utca': null,
  'Imre utca': null,
  'Indóház tér': null,
  'Ínfű utca': null,
  'Ingovány utca': null,
  'Ipoly sor': null,
  'Iringó utca': null,
  'Irinyi János utca': null,
  'Iskola utca': null,
  'István utca': null,
  'Ivánovics György utca': null,
  'Izabella híd': null,
  'Izabella utca': null,
  'Izsóp utca': null,
  'Jácint utca': null,
  'Jakab Lajos utca': null,
  'Jancsó Miklós utca': null,
  'Jankovich utca': null,
  'János-ér út': null,
  'Jász utca': null,
  'Jávorka utca': null,
  'Jázmin utca': null,
  'Jerney utca': null,
  'Jobb fasor': null,
  'Jókai utca': null,
  'Jolánka utca': null,
  'Jósika utca': null,
  'József Attila sugárút': null,
  'Judit utca': null,
  'Juharfás utca': null,
  'Juhász Gyula utca': null,
  'Júlia utca': null,
  'Kabóca utca': null,
  'Kácsa utca': null,
  'Kadarka utca': null,
  'Káka utca': null,
  'Kakukkfű utca': null,
  'Kakukk utca': null,
  'Kalász utca': null,
  'Kállay Albert utca': null,
  'Kálmán köz': null,
  'Kálmány Lajos utca': null,
  'Kálvária sugárút': null,
  'Kálvária tér': null,
  'Kálvin tér': null,
  'Kamarási utca': null,
  'Kamaratöltés': null,
  'Kamilla utca': null,
  'Kandó Kálmán utca': null,
  'Kanizsai utca': null,
  'Kankalin utca': null,
  'Kántor utca': null,
  'Kapás utca': null,
  'Kapisztrán út': null,
  'Kapitány utca': null,
  'Kápolna utca': null,
  'Kapor utca': null,
  'Kapu köz': null,
  'Karánsebesi utca': null,
  'Kárász utca': null,
  'Károlyi utca': null,
  'Kassai utca': null,
  'Kassák utca': null,
  'Kaszás utca': null,
  'Katalin utca': null,
  'Katáng utca': null,
  'Kátay utca': null,
  'Katica utca': null,
  'Katona József utca': null,
  'Kavics utca': null,
  'Kazinczy utca': null,
  'Kece utca': null,
  'Kecsege utca': null,
  'Kecskeméti utca': null,
  'Kékfestő utca': null,
  'Kékperje utca': null,
  'Kék utca': null,
  'Kelemen László utca': null,
  'Keleti út': null,
  'Kemes utca': null,
  'Kendergyári utca': null,
  'Kenguru köz': null,
  'Kenyérgyári út': null,
  'Kenyérvári sor': null,
  'Kénytelen sor': null,
  'Kerékgyártó utca': null,
  'Kereskedő köz': null,
  'Kereszttöltés utca': null,
  'Kereszt utca': null,
  'Kérész utca': null,
  'Kertész utca': null,
  'Késmárki utca': null,
  'Keszeg utca': null,
  'Kétérköz utca': null,
  'Kettőshatári út': null,
  'Kézdi utca': null,
  'Kígyószisz utca': null,
  'Kígyó utca': null,
  'Kikindai utca': null,
  'Kikirics utca': null,
  'Kikötő sor': null,
  'Kinizsi Pál utca': null,
  'Kisbaktói út': null,
  'Kisbogáros utca': null,
  'Kiserdő sor': null,
  'Kisfaludy utca': null,
  'Kiskert utca': null,
  'Kis köz': null,
  'Kismartoni utca': null,
  'Kiss Ernő utca': null,
  'Kiss Ferenc utca': null,
  'Kiss Menyhért utca': null,
  'Kisszőlő utca': null,
  'Kisteleki Ede utca': null,
  'Kisteleki út': null,
  'Kis-Tisza utca': null,
  'Kisvasút sor': null,
  'Kivi utca': null,
  'Klapka tér': null,
  'Klára utca': null,
  'Klauzál tér': null,
  'Kőbárány utca': null,
  'Kockaház utca': null,
  'Kokárda utca': null,
  'Kökény utca': null,
  'Kökörcsin utca': null,
  'Kókusz utca': null,
  'Kölcsey tér': null,
  'Kölcsey utca': null,
  'Kollégiumi út': null,
  'Koloszár udvar': null,
  'Kolozsvári tér': null,
  'Költő utca': null,
  'Kombinát köz': null,
  'Kömény utca': null,
  'Kond utca': null,
  'Könyves Kálmán köz': null,
  'Koppány köz': null,
  'Korányi fasor': null,
  'Korda utca': null,
  'Kormányos utca': null,
  'Körömvirág utca': null,
  'Korondi utca': null,
  'Kőrösmező utca': null,
  'Kőrös sor': null,
  'Körte utca': null,
  'Körtöltés': null,
  'Körtöltés utca': null,
  'Kosbor köz': null,
  'Kossuth Lajos sugárút': null,
  'Kossuth utca': null,
  'Koszorú utca': null,
  'Kovács udvar': null,
  'Kövidinka utca': null,
  'Közép fasor': null,
  'Közép-kapu utca': null,
  'Közép kikötő sor': null,
  'Kristály utca': null,
  'Krúdy Gyula utca': null,
  'Kubikos utca': null,
  'Kukorica utca': null,
  'Kukovetz Nana utca': null,
  'Küküllői utca': null,
  'Külüs köz': null,
  'Kundombi utca': null,
  'Kun utca': null,
  'Kürt utca': null,
  'Kuruc utca': null,
  'Kurucvölgyi út': null,
  'Kürü sor': null,
  'Kút utca': null,
  'Ladvánszky utca': null,
  'Lajta utca': null,
  'Laktanya utca': null,
  'Láma utca': null,
  'Láng Imre utca': null,
  'Lant utca': null,
  'Lányi Béla utca': null,
  'Láp utca': null,
  'Laura utca': null,
  'Leányszállás köz': null,
  'Lechner tér': null,
  'Léda utca': null,
  'Légió utca': null,
  'Legyezőfű köz': null,
  'Lehel utca': null,
  'Lékai utca': null,
  'Lendvai utca': null,
  'Lengyel udvar': null,
  'Lengyel utca': null,
  'Lenkey utca': null,
  'Lepke utca': null,
  'Levél utca': null,
  'Levendula utca': null,
  'Lidicei tér': null,
  'Liga utca': null,
  'Liget sor': null,
  'Lile utca': null,
  'Liliom köz': null,
  'Liliom utca': null,
  'Lilla utca': null,
  'Limány köz': null,
  'Liszt Ferenc sétány': null,
  'Liszt utca': null,
  'Lizinka köz': null,
  'Lőcsei utca': null,
  'Lomb utca': null,
  'Lomnici utca': null,
  'Londoni körút': null,
  'Lövölde utca': null,
  'Lőwy Sándor utca': null,
  'Lúdvári utca': null,
  'Lugas utca': null,
  'Mácsonya utca': null,
  'Madách utca': null,
  'Madarász utca': null,
  'Magas utca': null,
  'Magdolna utca': null,
  'Máglya sor': null,
  'Magtár köz': null,
  'Magyar utca': null,
  'Majális utca': null,
  'Majdáni sor': null,
  'Major utca': null,
  'Május 1. utca': null,
  'Makai út': null,
  'Makkoserdő sor': null,
  'Makkosházi körút': null,
  'Málna utca': null,
  'Malom utca': null,
  'Mályvarózsa utca': null,
  'Mályva utca': null,
  'Mandarin utca': null,
  'Mandula utca': null,
  'Máramarosi utca': null,
  'Margaréta utca': null,
  'Margit utca': null,
  'Mária utca': null,
  'Markovits Iván utca': null,
  'Márna utca': null,
  'Maróczy Géza tér': null,
  'Marostői utca': null,
  'Marostorok utca': null,
  'Maros utca': null,
  'Maróthy Gergely tér': null,
  'Maróti utca': null,
  'Mars tér': null,
  'Márták dűlő': null,
  'Martonosi utca': null,
  'Márvány utca': null,
  'Máté utca': null,
  'Mátra köz': null,
  'Matty tér': null,
  'Mátyás király tér': null,
  'Mátyás király utca': null,
  'Matyparti utca': null,
  'MÁV utca': null,
  'Mayer Miklós utca': null,
  'Mazsola utca': null,
  'Medveszőlő utca': null,
  'Meggyfa utca': null,
  'Méh utca': null,
  'Melinda utca': null,
  'Menhely utca': null,
  'Menta utca': null,
  'Mérey utca': null,
  'Mertz Tibor utca': null,
  'Mester utca': null,
  'Metro park': null,
  'oló': null,
  'Mező utca': null,
  'Mikes Kelemen utca': null,
  'Miklós utca': null,
  'Mikszáth Kálmán utca': null,
  'Mimóza utca': null,
  'Mogyoró utca': null,
  'Moholi utca': null,
  'Mokrini utca': null,
  'Molnár utca': null,
  'Móra Ferenc híd': null,
  'Mórahegyi út': null,
  'Móra utca': null,
  'Móravárosi körút': null,
  'Móricz Zsigmond utca': null,
  'Moszkvai körút': null,
  'Mozdony utca': null,
  'Műhely utca': null,
  'Munkácsy utca': null,
  'Munkás köz': null,
  'Munkás utca': null,
  'Murányi utca': null,
  'Mura utca': null,
  'Muskátli utca': null,
  'Muskó köz': null,
  'Muskotály utca': null,
  'Muslinca utca': null,
  'Mustár utca': null,
  'Must utca': null,
  'Műves út': null,
  'Nadályfű utca': null,
  'Nádas utca': null,
  'Nádor utca': null,
  'Nagybaktói út': null,
  'Nagybecskereki utca': null,
  'Nagybercsényi utca': null,
  'Nagy Jenő utca': null,
  'Nagykikinda utca': null,
  'Nagyrét utca': null,
  'Nagyszeg utca': null,
  'Nagyszéki út': null,
  'Nagyszombati utca': null,
  'Napfény köz': null,
  'Napos út': null,
  'Napraforgó utca': null,
  'Napsugár utca': null,
  'Nap utca': null,
  'Narancs utca': null,
  'Naspolya utca': null,
  'Nefelejcs utca': null,
  'Négyház utca': null,
  'Negyvennyolcas utca': null,
  'Nemes takács utca': null,
  'Németh András utca': null,
  'Nemzetőr sor': null,
  'Népdal utca': null,
  'Népkert sor': null,
  'Nőszőfű utca': null,
  'Nyárfa utca': null,
  'Nyár köz': null,
  'Nyilassy utca': null,
  'Nyíl utca': null,
  'Nyírfa utca': null,
  'Nyitra utca': null,
  'Nyugati sor': null,
  'Óbébai utca': null,
  'Ocskó utca': null,
  'Ökörszem utca': null,
  'Október 6. utca': null,
  'Olajos utca': null,
  'Oldal utca': null,
  'Olt utca': null,
  'Oltványi utca': null,
  'Orczy István utca': null,
  'Öreghegy dűlő': null,
  'Öreghegyi utca': null,
  'Orgona utca': null,
  'Őrlő köz': null,
  'Oroszlán utca': null,
  'Orsolya utca': null,
  'Orsovai utca': null,
  'Ortutay utca': null,
  'Örvény utca': null,
  'Orvos köz': null,
  'Oskola utca': null,
  'Ostrom utca': null,
  'Őszibarack utca': null,
  'Osztrovszky utca': null,
  'Ősz utca': null,
  'Öthalom utca': null,
  'Ötház utca': null,
  'Otthon utca': null,
  'Óvoda utca': null,
  'Pacsirta utca': null,
  'Pajtás utca': null,
  'Palackozó utca': null,
  'Palánk': null,
  'Palánkai utca': null,
  'Palánta utca': null,
  'Pálfy utca': null,
  'Palics köz': null,
  'Pálma utca': null,
  'Palóc utca': null,
  'Pál utca': null,
  'Pálya tér': null,
  'Páncél köz': null,
  'Pancsovai utca': null,
  'Panda tér': null,
  'Pápai utca': null,
  'Paprika utca': null,
  'Párizsi körút': null,
  'Párlófű utca': null,
  'Parobek Alajos utca': null,
  'Passzázs sor': null,
  'Pasztinák köz': null,
  'Pásztortáska köz': null,
  'Pásztor utca': null,
  'Pázsit utca': null,
  'Pécskai utca': null,
  'Pentelei sor': null,
  'Petneházy utca': null,
  'Petőfi Sándor sugárút': null,
  'Petőfi utca': null,
  'Petresi utca': null,
  'Petrozsényi utca': null,
  'Pihenő utca': null,
  'Pilisi utca': null,
  'Pillangó utca': null,
  'Pille utca': null,
  'Pillich Kálmán utca': null,
  'Pimpó utca': null,
  'Pintér József utca': null,
  'Pinty utca': null,
  'Pipacs utca': null,
  'Pipiske utca': null,
  'Pipitér utca': null,
  'Piroska tér': null,
  'Piszke utca': null,
  'Pisztácia utca': null,
  'Pitypang utca': null,
  'Pók utca': null,
  'Ponty utca': null,
  'Postás utca': null,
  'Pöstyéni utca': null,
  'Pósz Jenő utca': null,
  'Pozsonyi Ignác utca': null,
  'Pulz utca': null,
  'Puskás utca': null,
  'Püspök utca': null,
  'Pusztaszeri utca': null,
  'Rába utca': null,
  'Rábéi utca': null,
  'Radnóti utca': null,
  'Rahói utca': null,
  'Rákóczi utca': null,
  'Raktár köz': null,
  'Rebarbara utca': null,
  'Réce utca': null,
  'Régész tér': null,
  'Regina utca': null,
  'Régiposta utca': null,
  'Reizner János utca': null,
  'Rekettye utca': null,
  'Remény utca': null,
  'Remete utca': null,
  'Rendező tér': null,
  'Rengey utca': null,
  'Répás utca': null,
  'Rerrich Béla tér': null,
  'Retek utca': null,
  'Réti utca': null,
  'Révai utca': null,
  'Rév utca': null,
  'Rezeda utca': null,
  'Rezgőfű köz': null,
  'Rézöntő utca': null,
  'Réz utca': null,
  'Ribizli utca': null,
  'Rigómező utca': null,
  'Rigó utca': null,
  'Ringló utca': null,
  'Rohonci utca': null,
  'Rókusi körút': null,
  'Római körút': null,
  'Rom utca': null,
  'Róna utca': null,
  'Roosevelt tér': null,
  'Rosta köz': null,
  'Röszkei utca': null,
  'Rövid köz': null,
  'Rövid utca': null,
  'Rozmaring utca': null,
  'Rózsaszéki utca': null,
  'Rózsatő utca': null,
  'Rózsa utca': null,
  'Rozsnok utca': null,
  'Rozsnyói utca': null,
  'Rügy utca': null,
  'Ruszti utca': null,
  'Sáfrány utca': null,
  'Sajka utca': null,
  'Sándor utca': null,
  'Sarkantyú utca': null,
  'Sárkány utca': null,
  'Sarlófű utca': null,
  'Sarló utca': null,
  'Sárosi utca': null,
  'Sas utca': null,
  'Sás utca': null,
  'Selmeci utca': null,
  'Selyem utca': null,
  'Semmelweis utca': null,
  'Sepsi utca': null,
  'Seres János utca': null,
  'Siha köz': null,
  'Sikér köz': null,
  'Sík Sándor utca': null,
  'Sínpár sor': null,
  'Sípos Iván utca': null,
  'Sirály utca': null,
  'Sóhordó utca': null,
  'Sólya utca': null,
  'Sólyom utca': null,
  'Sömlyék út': null,
  'Somogyi utca': null,
  'Som utca': null,
  'Sőtér István köz': null,
  'Só utca': null,
  'Sportpálya út': null,
  'StefániaStrand utca': null,
  'Subasa út': null,
  'Sügér utca': null,
  'Süllő utca': null,
  'Sulyom út': null,
  'Süveg utca': null,
  'Szabadkai út': null,
  'Szabadság tér': null,
  'Szabad sajtó utca': null,
  'Szabó János utca': null,
  'Szajáni utca': null,
  'Szakolcai utca': null,
  'Szák út': null,
  'Szalmáskert út': null,
  'Szamóca utca': null,
  'Szamos utca': null,
  'Szántó Kovács János utca': null,
  'Szántó utca': null,
  'Szappanos utca': null,
  'Szarkaláb utca': null,
  'Szarvas köz': null,
  'Szatymazi utca': null,
  'Száva utca': null,
  'Széchenyi István utca': null,
  'Széchenyi tér': null,
  'Szécsi utca': null,
  'Szeder utca': null,
  'Szegedi pihenőhely': null,
  'Szegfű utca': null,
  'Székely sor': null,
  'Szekerce utca': null,
  'Szekeres utca': null,
  'Széksósi út': null,
  'Szék utca': null,
  'Szellő utca': null,
  'Szélmalom utca': null,
  'Szélső sor': null,
  'Szél utca': null,
  'Széna utca': null,
  'Szende Béla utca': null,
  'Szendrey Júlia utca': null,
  'Szent Antal utca': null,
  'Szent Ferenc utca': null,
  'Szent Gellért utca': null,
  'Szent-Györgyi Albert utca': null,
  'Szent György tér': null,
  'Szentháromság utca': null,
  'Szent István tér': null,
  'Szent János tér': null,
  'Szent László utca': null,
  'Szentmihályteleki utca': null,
  'Szent Mihály utca': null,
  'Szent Miklós utca': null,
  'Szent Rókus tér': null,
  'Szepesi utca': null,
  'Szerb utca': null,
  'Szercsika utca': null,
  'Szérűskerti sor': null,
  'Szérűskert utca': null,
  'Szigeti út': null,
  'Sziget utca': null,
  'Szigony utca': null,
  'Szikla utca': null,
  'Szilágyi utca': null,
  'Sziliszék út': null,
  'Szilléri sor': null,
  'Szilléri sugárút': null,
  'Szilva utca': null,
  'Szirom utca': null,
  'Szitakötő utca': null,
  'Szivárvány utca': null,
  'Szív utca': null,
  'Szívvirág utca': null,
  'Szöcske utca': null,
  'Szögi József utca': null,
  'Szőkefalvi-Nagy Béla utca': null,
  'Szőke Tisza utca': null,
  'Szőke utca': null,
  'Szolgáltató sor': null,
  'Szőlő utca': null,
  'Szondi György utca': null,
  'Szőregi út': null,
  'Szöri utca': null,
  'Szövetkezeti út': null,
  'Szövetség utca': null,
  'Szövő utca': null,
  'Sztriha Kálmán utca': null,
  'Szűcs utca': null,
  'Szúnyog utca': null,
  'Szurokfű utca': null,
  'Tabán utca': null,
  'Tábornok utca': null,
  'Tábor utca': null,
  'Takaréktár utca': null,
  'Taksony utca': null,
  'Talicska utca': null,
  'Talpas utca': null,
  'Tambura utca': null,
  'Tanács utca': null,
  'Táncsics Mihály utca': null,
  'Tanító tér': null,
  'Tápai utca': null,
  'Tápé széle': null,
  'Tapodi utca': null,
  'Tapolcsányi utca': null,
  'Tarján széle': null,
  'Tárkony utca': null,
  'Tarló utca': null,
  'Tarnóci utca': null,
  'Tárnokfű utca': null,
  'Tárogató utca': null,
  'Tas utca': null,
  'Tátra tér': null,
  'Tavasz utca': null,
  'Távol utca': null,
  'Téglagyár utca': null,
  'Tégla köz': null,
  'Téglaverő utca': null,
  'Tegzes utca': null,
  'Teleki utca': null,
  'Temesvári körút': null,
  'Temesvári utca': null,
  'Temető utca': null,
  'Templom tér': null,
  'Tenkes köz': null,
  'Terehalmi út': null,
  'Teréz utca': null,
  'Termelő utca': null,
  'Testvériség köz': null,
  'Teve utca': null,
  'Textilgyári út': null,
  'Thököly utca': null,
  'Tigér utca': null,
  'Tigris utca': null,
  'Tímár utca': null,
  'Tinódi utca': null,
  'Tisza köz': null,
  'Tisza Lajos körút': null,
  'Tisza Lajos utca': null,
  'Tisza töltés': null,
  'Tiszavirág utca': null,
  'Titeli utca': null,
  'Tizenhetedik út': null,
  'Tóbiás György utca': null,
  'Toboz utca': null,
  'Toldy utca': null,
  'Tölgyes utca': null,
  'Tölgyfa utca': null,
  'Töltés utca': null,
  'Tömörkény utca': null,
  'Tompai kapu út': null,
  'Tompa Mihály utca': null,
  'Tópart utca': null,
  'Topolya sor': null,
  'Tordai utca': null,
  'Torma utca': null,
  'Torockói utca': null,
  'Törökkanizsa utca': null,
  'Török utca': null,
  'Törökverő utca': null,
  'Torontál tér': null,
  'Törő utca': null,
  'Tóth János dűlő': null,
  'Tó utca': null,
  'Tőzike utca': null,
  'Trafik utca': null,
  'Traktor utca': null,
  'Trencséni utca': null,
  'Trombita utca': null,
  'Tücsök utca': null,
  'Tulipán utca': null,
  'Tündér utca': null,
  'Tünde tér': null,
  'Turbolya utca': null,
  'Turista utca': null,
  'Turul utca': null,
  'Tüsök utca': null,
  'Tüzép köz': null,
  'Túzok utca': null,
  'Tűzoltó utca': null,
  'Udvardi János utca': null,
  'Udvarhelyi utca': null,
  'Ugar utca': null,
  'Új Élet utca': null,
  'Újföld sor': null,
  'Újhelyi köz': null,
  'Ujjaskosbor utca': null,
  'Új tér': null,
  'Újvárosi utca': null,
  'Újvidéki utca': null,
  'Újvilág utca': null,
  'Ungvári utca': null,
  'Űrhajós utca': null,
  'Üröm utca': null,
  'Üstökös utca': null,
  'Úszó út': null,
  'Útifű utca': null,
  'Uzsoki utca': null,
  'Vadalma utca': null,
  'Vadas Márton utca': null,
  'Vadászház dűlő': null,
  'Vadász utca': null,
  'Vadkerti tér': null,
  'Vadliba utca': null,
  'Vadmacska utca': null,
  'Vadmurok utca': null,
  'Vadrózsa sor': null,
  'Vágány utca': null,
  'Vágóhíd utca': null,
  'Vágóhorog utca': null,
  'Vág utca': null,
  'Vajda utca': null,
  'Vajk utca': null,
  'Vak Bottyán utca': null,
  'Váltó utca': null,
  'Vályog köz': null,
  'Vályogos utca': null,
  'Vám tér': null,
  'Vándor köz': null,
  'Vándor utca': null,
  'Vánky József utca': null,
  'Váradi utca': null,
  'Varga utca': null,
  'Városgazda sor': null,
  'Varsa utca': null,
  'Vártó utca': null,
  'Vár utca': null,
  'Vásárhelyi Pál utca': null,
  'Vásártér sor': null,
  'Vásár utca': null,
  'Vasas Szent Péter utca': null,
  'Vasfű utca': null,
  'Vasgyár utca': null,
  'Vaskapu utca': null,
  'Vaspálya utca': null,
  'Vasutas sor': null,
  'Vas utca': null,
  'Vasúti rakodó': null,
  'Vasvári Pál utca': null,
  'Vaszy Viktor tér': null,
  'Védőnő utca': null,
  'Vedres utca': null,
  'Végvári utca': null,
  'Vellay Imre utca': null,
  'Venyige utca': null,
  'Véradó utca': null,
  'Verbéna utca': null,
  'Vércse utca': null,
  'Verecke utca': null,
  'Veres ács utca': null,
  'Vereshomok dűlő': null,
  'Vereshomok út': null,
  'Veres Péter utca': null,
  'Verseci utca': null,
  'Verseny utca': null,
  'Vértói út': null,
  'Vezér utca': null,
  'Victor Hugo utca': null,
  'Vidra utca': null,
  'Vikunya utca': null,
  'Világos utca': null,
  'Vincellér utca': null,
  'Vinkler László út': null,
  'Viola utca': null,
  'Virág utca': null,
  'Vitéz köz': null,
  'Vitéz utca': null,
  'Vitorla utca': null,
  'Vívó köz': null,
  'Viza utca': null,
  'Vízipók utca': null,
  'Víztorony tér': null,
  'Vlasics Károly utca': null,
  'Vöcsök utca': null,
  'Völgyérhát utca': null,
  'Vörösmarty utca': null,
  'Wagner Viktória utca': null,
  'Wallisch Kálmán utca': null,
  'Wesselényi utca': null,
  'Wimmer Fülöp utca': null,
  'Ybl Miklós utca': null,
  'Zádori utca': null,
  'Zágon utca': null,
  'Zágráb utca': null,
  'Zákány utca': null,
  'Zalán utca': null,
  'Zápor út': null,
  'Zárda utca': null,
  'Zárt utca': null,
  'Zászló utca': null,
  'Zátony utca': null,
  'Zengő utca': null,
  'Zentai utca': null,
  'Zocskár udvar': null,
  'Zöldfási út': null,
  'Zöldfa utca': null,
  'Zoltánfy István utca': null,
  'Zoltán utca': null,
  'Zólyomi utca': null,
  'Zombori utca': null,
  'Zrínyi utca': null,
  'Zsák köz': null,
  'Zsálya utca': null,
  'Zsámbokréti sor': null,
  'Zsilip utca': null,
  'Zsil utca': null,
  'Zsitva sor': null,
  'Zsoldos köz': null,
  'Zsolnai utca': null,
  'Zsombói út': null,
  'Zsombolyai utca': null,
  'Zsótér utca': null,
  'Zsukov tér': null,
  'Zsurló utca': null,
  'Anna-kút': null,
};

